input.onButtonPressed(Button.A, function () {
    music.playTone(165, music.beat(BeatFraction.Half))
    music.playTone(208, music.beat(BeatFraction.Half))
    music.playTone(247, music.beat(BeatFraction.Half))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.playTone(415, music.beat(BeatFraction.Half))
    music.playTone(494, music.beat(BeatFraction.Half))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.setTempo(111)
    music.ringTone(262)
    music.playTone(220, music.beat(BeatFraction.Eighth))
    music.playTone(185, music.beat(BeatFraction.Eighth))
    music.playTone(220, music.beat(BeatFraction.Eighth))
    music.playTone(247, music.beat(BeatFraction.Eighth))
    music.playTone(277, music.beat(BeatFraction.Eighth))
    music.playTone(220, music.beat(BeatFraction.Eighth))
    music.playTone(277, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(277, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.setTempo(74)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.setTempo(111)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 2; index++) {
        music.playTone(415, music.beat(BeatFraction.Eighth))
        music.playTone(330, music.beat(BeatFraction.Eighth))
        music.playTone(247, music.beat(BeatFraction.Eighth))
        music.playTone(208, music.beat(BeatFraction.Eighth))
    }
    music.setTempo(148)
    for (let index = 0; index < 3; index++) {
        music.playTone(415, music.beat(BeatFraction.Eighth))
        music.playTone(330, music.beat(BeatFraction.Eighth))
        music.playTone(247, music.beat(BeatFraction.Eighth))
    }
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.setTempo(74)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.setTempo(111)
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.setTempo(74)
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.setTempo(111)
})
